spring:
  application:
    name: QuantNexus
  profiles:
    active: dev # Defaults to H2 if you just hit "Run" in your IDE

server:
  port: 8080

app:
  security:
    jwt:
      expiration: 86400000 # 24 hours globally

  admin:
    email: manishneelambar@gmail.com
    password: Admin@5200